# ============================================================
#  RoboMaster 视觉 — 多人配置
#  格式: player=<名字>,path=<项目路径>,label=<显示名>
#  default= 指定超时无人选择时默认启动谁
#  timeout= 无人选择时的倒计时秒数, 0=不等待直接启动默认
# ============================================================

[dyx]
path=/home/dyx/桌面/bean_sorting_framework
label=阿东-视觉识别

[player2]
path=/home/xxx/桌面/vision_project
label=预留-队员2

[player3]
path=/home/xxx/桌面/vision_project
label=预留-队员3

[player4]
path=/home/xxx/桌面/vision_project
label=预留-队员4

[config]
default=dyx
timeout=5
